spring.application.name=pos-system
spring.data.mongodb.uri=mongodb+srv://Gayal_db_user:K42HRWzcnPIWw5Cs@cluster0.xy8llul.mongodb.net/POS_Sathutu?appName=Cluster0
spring.data.mongodb.database=POS_Sathutu

# Server Configuration
server.port=8080
server.servlet.context-path=/

# Logging
logging.level.root=INFO
logging.level.com.posystem=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
